version: '2.0'

services:
  ethereum:
    build: .
    image: ethereum/private-chain
    restart: always
    ports:
      - 8545:8545
      - 30303:30303
    volumes: 
      - ./workspace:/workspace

  explorer:
    image: jamess010/explorer
    restart: always
    ports:
      - 8000:8000
    command: ./run.sh

