version: '2.0'

services:
  node01:
    image: jamess010/ethereum
    restart: always
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - "/home/tjian/extData/blockchain/jamess010-explore/node01/mine.sh:/mine.sh"

  node02:
    image: jamess010/ethereum
    restart: always
    ports:
      - 8555:8555
      - 30323:30323
    volumes:
      - "/home/tjian/extData/blockchain/jamess010-explore/node02/mine.sh:/mine.sh"
    depends_on: [node01]

  explorer:
    image: jamess010/explorer
    restart: always
    ports:
      - 8000:8000
    volumes:
      - "/home/tjian/extData/blockchain/jamess010-explore/explorer/app.js:/explorer/app/app.js"
      - "/home/tjian/extData/blockchain/jamess010-explore/explorer/package.json:/explorer/package.json"
      - "/home/tjian/extData/blockchain/jamess010-explore/explorer/mainController.js:/explorer/app/scripts/controllers/mainController.js"

  ethnetapi:
    image: jamess010/ethnetapi
    restart: always
    volumes:
      - "/home/tjian/extData/blockchain/jamess010-explore/ethnetapi/startscript.sh:/home/ethnetintel/eth-net-intelligence-api/startscript.sh"
      - "/home/tjian/extData/blockchain/jamess010-explore/ethnetapi/node01.json:/home/ethnetintel/eth-net-intelligence-api/node01.json"
      - "/home/tjian/extData/blockchain/jamess010-explore/ethnetapi/node02.json:/home/ethnetintel/eth-net-intelligence-api/node02.json"

  ethstats:
    image: jamess010/ethstats
    restart: always
    environment:
      WS_SECRET: "test"
    ports:
      - 3000:3000

